### ISSUE TITLE
[QUESTION] Select disabled days

### ISSUE THREAD

**Issue by coloo002** [rajeshwarpatlolla/ionic-datepicker#318] opened 2017-05-16 15:17 UTC
When i open the datepicker it shows me the correct data (with days enabled and disabled correctly). But I can change the month no matter if the month is enabled or disabled, which is incorrect.. Please, see my video to know more about the problem: 

https://streamable.com/0xic0

My code is the following:

    var ipObj1 = {
        callback: callback, 
        inputDate: new Date(),
        titleLabel: 'Seleccione una fecha',
        setLabel: 'Cancelar',
        todayLabel: 'Hoy',
        closeLabel: 'Aceptar',
        mondayFirst: true,
        from: new Date(2016, 5, 1),
        to: new Date(2016, 6, 15),
        weeksList: ["D", "L", "M", "MI", "J", "V", "S"],
        monthsList: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"],
        templateType: 'popup',
        showTodayButton: false,
        dateFormat: 'dd MMMM yyyy',

         closeOnSelect: false
    };

**EDIT:** Only happens when I'm using local files from this library. But... Why is the reason that without using bower happens and if I copy the same code I get this bug? 

Thank you

**Comment by rajeshwarpatlolla** [comment] 2017-11-06 04:46
Duplicate of #258

**Closed by rajeshwarpatlolla** 2017-11-06 04:46 UTC
