### ISSUE TITLE
closeOnSelect doesn't work on version 0.9.0

### ISSUE THREAD

**Issue by chompunut** [rajeshwarpatlolla/ionic-datepicker#112] opened 2015-11-05 12:43 UTC
I installed version 0.9.0 the closeOnSelect doesn't work. I set it to true but when I select a date, the popup doesn't close and no error message.

```
$scope.datepickerObject = {
    closeOnSelect: true, 
    templateType: 'popup',
    to: new Date(),
    callback: function (date) { 
          console.log('callback');
    }
};
```

**Comment by renekorss** [comment] 2015-11-05 13:27
`closeOnSelect` was added by me onyl to days ago. So it's not in 0.9.0 release. Update you version to use master branch version and it will work.

**Comment by chompunut** [comment] 2015-11-05 13:58
I've installed the master branch but the issue still happen. Please see https://github.com/rajeshwarpatlolla/ionic-datepicker/issues/111

**Comment by rajeshwarpatlolla** [comment] 2015-11-05 16:30
This feature will make the user feel strange. Let's say when a user clicks on a date but don't want to select that date, even in that case the popup will close, again the user have to open it again. So i don't think, this feature will be used by so many. I suggest this feature to be implemented those who wish, but not as part of this component. Suggestions are welcome.

**Comment by chompunut** [comment] 2015-11-05 16:58
After I sent app to my users, they prefer the close on select function because it does like date picker in many web sites are using and it doesn't need many clicks which is suitable for mobile device. For example, the app use for planing many tasks in a day.

**Comment by rajeshwarpatlolla** [comment] 2015-11-05 17:00
So, it's a kind of on demand feature. I was discussing with few people about this feature, most of them are not preferring this way, as it makes most of the users confuse. The user may wish to select day first and then month and then year, in this case the user should be abel to do all in one go. If we have this feature, then the user has to open the datepicker for 3 times.

**Comment by chompunut** [comment] 2015-11-05 17:22
But the version 0.9.0 doesn't support the way to select date first and then month and then year. When I select date first and then month, the picker doesn't highlight date on the selected month.

For example, I select the date 3nd on November then change month to April and click on Set button. The output date still be November 3 not April 3. This is why my user confuse about. 

So, I think the close on select should be an option for developer to customize it behavior.

**Comment by renekorss** [comment] 2015-11-06 12:54
I can confirm what @chompunut said. In ver 0.9.0. If i check date and then change month, then the date wont be that months. Chaning month dosen't change selected date.

**Comment by harishanandan** [comment] 2015-11-22 07:14
Hi can Any one plz help me with this datepicker I have installed everything but I could not get modal .can any one plz suggest

**Comment by djoks** [comment] 2015-12-25 15:49
First of all, great plugin, really handy :) however I am in agreement that closeOnSelect should be an option for the developer (doesn't work for me currently), most of my users prefer that option as well, considering how in my case a user can only select a date within a period of 7 days after tomorrow. In which case there should also be options to hide all the buttons.  Also can you please tell me if there is a way to generally change the theme color of the plugin from one central setting. Thank you in advance. :)

**Comment by pharindoko** [comment] 2016-01-04 13:59
I can confirm....
closeOnSelect 
doesn't work in the current released bower version as it is not implemented and 
does not work with #master version because of errors - it is implemented.

Hope that this will be fixed  - I like this datepicker - and yeah I would need this option too.

**Comment by mwagena** [comment] 2016-02-16 11:04
Hi,
This issue also occurs in the master branch, could you give an estimate on when the fix will be made?
Thanks in advance!

**Comment by rajeshwarpatlolla** [comment] 2016-02-16 11:07
I am trying to make few changes and once they are done, i will release a new version with this feature.

**Comment by erikakinga** [comment] 2016-02-29 11:23
+1

**Comment by rajeshwarpatlolla** [comment] 2016-03-17 06:24
Please check the new release [v1.0.0](https://github.com/rajeshwarpatlolla/ionic-datepicker/releases/tag/v1.0.0). This issue has been addressed.

**Closed by rajeshwarpatlolla** 2016-03-17 06:24 UTC
